### PR TITLE
First draft of a TypeScript version

### PR DESCRIPTION
**Pull request by EsterDanielYtterbrink**
I have a team learning TypeScript, and they do not use any of the other languages present. So I created a TS-version of this kata.

### CODE REVIEW

**Comment by EsterDanielYtterbrink** [comment]
There is something wrong with the matcher for the first test. I am on it.

**Comment by emilybache** [comment]
I'm happy to merge this whenever you say it's ready

**Comment by EsterDanielYtterbrink** [comment]
I think this is a valid translation to TypeScript, now as I changed the matcher. So @emilybache if you want to please merge it.

**Comment by emilybache** [comment]
Thankyou!

**Comment by EsterDanielYtterbrink** [comment]
My pleasure!

**Pull request merged**
